name: Scala CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up openjdk11
      uses: actions/setup-java@v1
      with:
        java-version: openjdk11
    - name: Run tests
      run: sbt test
